print (8 / 2 + 5 - -3 / 2)
print ("\"Khal Drogo's favorite word is \"athjahakar\"\"")
print ("Winter" + " " + "came" + " " + "for" + " " + "the" + " " + "House" + " " + "of" + " " + "Frey"".")
word = ("First text")
print (word)
word = ("Second text")
print (word)
a = input("What is your name? ")
print ("Helo," " " + a +"!")